import React, { useState } from 'react';
import { ShieldCheck, CheckCircle2, Download, Copy, ArrowRight, Activity, FileText, ExternalLink, Printer, Key, Shield, IndianRupee, Building2, PhoneCall, Zap, Lock } from 'lucide-react';
import { AppScreen, ComplaintData } from '../../types';

interface ConfirmationScreenProps {
  complaintData: ComplaintData;
  onNavigate: (screen: AppScreen) => void;
}

export const ConfirmationScreen: React.FC<ConfirmationScreenProps> = ({
  complaintData,
  onNavigate
}) => {
  const [copied, setCopied] = useState(false);

  const handleCopyId = () => {
    navigator.clipboard.writeText(complaintData.caseId);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadReport = () => {
    const bank = complaintData.bankDetails || {
      victimBank: 'State Bank of India (SBI)',
      amountLost: complaintData.financialLoss || '₹75,000',
      transactionIdOrUtr: '423189041289',
      suspectPhoneNumber: '+91 98765 43210',
      suspectUpiOrAccount: 'cyberfrauder@ybl',
      paymentApp: 'Google Pay (UPI)'
    };

    const reportText = `================================================================================
NATIONAL CYBERCRIME REPORTING PORTAL (1930) | CITIZEN FINANCIAL FRAUD DOCKET
Government of India - Ministry of Home Affairs (I4C)
================================================================================
1930 ACKNOWLEDGMENT NO: ${complaintData.caseId}
STATUS:                 TRANSMITTED TO BENEFICIARY BANK NODAL NETWORK (GOLDEN HOUR)
FILING TIMESTAMP:       ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} IST
INCIDENT CATEGORY:      ${complaintData.complaintType}
AMOUNT REPORTED:        ${bank.amountLost}
VICTIM BANK:            ${bank.victimBank}
UTR / TRANSACTION ID:   ${bank.transactionIdOrUtr}
SUSPECT IDENTIFIER:     ${bank.suspectUpiOrAccount} (${bank.suspectPhoneNumber})
PAYMENT METHOD:         ${bank.paymentApp}

--------------------------------------------------------------------------------
1. COMPLAINT NARRATIVE & MODUS OPERANDI
--------------------------------------------------------------------------------
${complaintData.narrative}

--------------------------------------------------------------------------------
2. ELECTRONIC EVIDENCE & SCREENSHOTS (${complaintData.evidenceList.length} FILES)
--------------------------------------------------------------------------------
${complaintData.evidenceList.map((e, i) => `[${i + 1}] ${e.name}
    Type:      ${e.category}
    Size:      ${e.size}
    Hash:      ${e.hash}
    Timestamp: ${e.timestamp}
`).join('\n')}

--------------------------------------------------------------------------------
3. STATUTORY NOTICE UNDER IT ACT 2000 & 1930 CFCFRMS
--------------------------------------------------------------------------------
This acknowledgment is generated by the Citizen Financial Cyber Fraud Reporting
and Management System (1930 CFCFRMS). An automated freeze broadcast is issued to
all destination banks/wallets to place a temporary lien on suspect balances.
================================================================================`;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CyberCrime_1930_Docket_${complaintData.caseId}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-[950px] mx-auto px-4 sm:px-6 pt-24 sm:pt-32 pb-16 space-y-8">
      {/* Confirmation Top Box */}
      <div className="glass-panel rounded-3xl p-8 sm:p-12 border border-[#5ffbd6]/40 text-center space-y-6 shadow-[0_0_50px_rgba(95,251,214,0.15)] relative overflow-hidden">
        <div className="w-20 h-20 rounded-3xl bg-[#112240] border-2 border-[#5ffbd6] flex items-center justify-center mx-auto text-[#5ffbd6] shadow-[0_0_30px_rgba(95,251,214,0.4)] animate-fade-in">
          <ShieldCheck className="w-10 h-10" />
        </div>

        <div className="space-y-2">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#112240] border border-[#5ffbd6]/40 text-[#5ffbd6] text-xs font-mono tracking-widest uppercase">
            <Zap className="w-3.5 h-3.5 text-[#5ffbd6]" />
            1930 Direct Bank Nodal Broadcast Active
          </div>
          <h1 className="text-3xl sm:text-4xl md:text-5xl font-extrabold text-white tracking-tight">
            Complaint Successfully Lodged
          </h1>
          <p className="text-sm sm:text-base text-[#bacac3] max-w-xl mx-auto font-sans leading-relaxed">
            Your complaint has been registered with the 1930 National Cybercrime Portal. An emergency lien request has been dispatched to beneficiary banks.
          </p>
        </div>

        {/* Case ID Callout Card */}
        <div className="p-4 sm:p-5 rounded-2xl bg-[#071324] border border-[#5ffbd6]/40 max-w-md mx-auto flex items-center justify-between gap-4">
          <div className="text-left font-mono">
            <span className="text-[10px] text-[#bacac3] uppercase block font-semibold">1930 Acknowledgment Number</span>
            <span className="text-lg sm:text-xl font-bold text-white tracking-wider">{complaintData.caseId}</span>
          </div>

          <button
            onClick={handleCopyId}
            className="px-3.5 py-2 rounded-xl bg-[#112240] hover:bg-[#1c2a41] border border-[#233554] text-[#5ffbd6] font-mono text-xs uppercase flex items-center gap-1.5 transition-colors"
          >
            <Copy className="w-3.5 h-3.5" />
            <span>{copied ? 'Copied!' : 'Copy ID'}</span>
          </button>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row items-center justify-center gap-3 pt-2">
          <button
            onClick={handleDownloadReport}
            className="w-full sm:w-auto bg-[#5ffbd6] hover:bg-[#38debb] text-[#041329] font-bold px-7 py-3.5 rounded-xl font-mono text-xs uppercase tracking-wider flex items-center justify-center gap-2 shadow-[0_0_20px_rgba(95,251,214,0.3)] hover:shadow-[0_0_25px_rgba(95,251,214,0.5)] active:scale-[0.98] transition-all"
          >
            <Download className="w-4 h-4 text-[#041329]" />
            <span>Download Certified 1930 Docket</span>
          </button>

          <button
            onClick={() => onNavigate('case_tracker')}
            className="w-full sm:w-auto bg-[#112240] hover:bg-[#1c2a41] border border-[#233554] text-white px-7 py-3.5 rounded-xl font-mono text-xs uppercase tracking-wider flex items-center justify-center gap-2 transition-all"
          >
            <Activity className="w-4 h-4 text-[#5ffbd6]" />
            <span>Track Bank Lien Status</span>
          </button>
        </div>
      </div>

      {/* What Happens Next 3-Step Interactive Timeline */}
      <div className="space-y-4">
        <div className="text-center space-y-1">
          <h2 className="text-xl sm:text-2xl font-bold text-white tracking-tight">
            What Happens in the Next 24 Hours
          </h2>
          <p className="text-xs sm:text-sm text-[#bacac3] font-sans">
            Standard Citizen Financial Cyber Fraud Response & Recovery Pipeline
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="glass-card rounded-2xl p-6 border border-[#233554] space-y-3 relative">
            <div className="w-8 h-8 rounded-full bg-[#5ffbd6]/15 border border-[#5ffbd6]/40 flex items-center justify-center font-mono text-xs font-bold text-[#5ffbd6]">
              1
            </div>
            <h3 className="font-semibold text-white text-sm">Instant Bank Lien Freeze</h3>
            <p className="text-xs text-[#bacac3] leading-relaxed font-sans">
              The 1930 CFCFRMS engine alerts the recipient bank nodal officer to immediately put on hold the disputed amount in suspect accounts.
            </p>
          </div>

          <div className="glass-card rounded-2xl p-6 border border-[#233554] space-y-3 relative">
            <div className="w-8 h-8 rounded-full bg-[#5ffbd6]/15 border border-[#5ffbd6]/40 flex items-center justify-center font-mono text-xs font-bold text-[#5ffbd6]">
              2
            </div>
            <h3 className="font-semibold text-white text-sm">Cyber Cell Verification</h3>
            <p className="text-xs text-[#bacac3] leading-relaxed font-sans">
              Your local district Cyber Crime Police Station reviews the evidence docket and registers the formal First Information Report (FIR).
            </p>
          </div>

          <div className="glass-card rounded-2xl p-6 border border-[#233554] space-y-3 relative">
            <div className="w-8 h-8 rounded-full bg-[#5ffbd6]/15 border border-[#5ffbd6]/40 flex items-center justify-center font-mono text-xs font-bold text-[#5ffbd6]">
              3
            </div>
            <h3 className="font-semibold text-white text-sm">Court Order & Refund</h3>
            <p className="text-xs text-[#bacac3] leading-relaxed font-sans">
              Under Section 457 CrPC, the frozen funds are processed for refund back into your source bank account with minimal hassle.
            </p>
          </div>
        </div>
      </div>

      {/* Return to Home link */}
      <div className="text-center pt-4">
        <button
          onClick={() => onNavigate('home')}
          className="text-xs font-mono text-[#bacac3] hover:text-[#5ffbd6] transition-colors"
        >
          &larr; Return to National Portal Home
        </button>
      </div>
    </div>
  );
};

